### PR TITLE
add short-cut for expressions only having a numeric part

### PR DESCRIPTION
**Pull request by ManuelHu**
this speeds up loading our LEGEND geometry from GDML by ~10 times.

### CODE REVIEW

**Comment by gipert** [comment]
@stewartboogert good to merge and release a patch version?

**Comment by stewartboogert** [comment]
> this speeds up loading our LEGEND geometry from GDML by ~10 times.

Is there a lot of tesselated in your geometry?

**Comment by stewartboogert** [comment]
Very happy with this. Please merge and release a patch verion

**Comment by gipert** [comment]
I just realized that there are a lot of unreleased changes in `main`, should I include them  and bump the minor version number?

**Comment by stewartboogert** [comment]
> I just realized that there are a lot of unreleased changes in `main`, should I include them and bump the minor version number?

Agreed. Lots of bug fixes, but there was some real developments in USD

**Pull request merged**
