### PR TITLE
docs: pin sphinx to >=7.2.2 in RTD build

### LINKED ISSUE #89: Documentation generation (readthedocs) failure
Tests fail when creating documentation #88 

Documentation generation works well on local Mac installation.

### PR DESCRIPTION
**Pull request by ManuelHu**
fixes #89 

We already had this issue in our other repositories over the last days.

### CODE REVIEW

**Comment by ManuelHu** [comment]
Okay, this procedure to require `sphinx>=7.2.2` does apparently not work...

**Comment by gipert** [comment]
So pinning a Sphinx version in `pyproject.toml` does not work? It should according to them: https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx

**Comment by ManuelHu** [comment]
From the link (emphasis added):
> [...] If you are using a metadata file to describe code dependencies like `setup.py`, `pyproject.toml`, or similar, **you can use the `extra_requirements`** option [...]

We don't use `extra_requirements` here, but directly pip install. So - I guess - it would not work.

**Comment by gipert** [comment]
Right, sorry, I forgot that we don't install pyg4ometry on RTD (takes too much time and resources). Thanks a Lot Manuel for fixing this -- merging.

**Pull request merged**
