### PR TITLE
Fluka (extruder, running and analysis)

### PR DESCRIPTION
**Pull request by stewartboogert**
**General FLUKA developments** 

Working 2d fluka extruder
* Tidy CGAL 2d decomposition operations
* Class to represent 2d structure
* Start of implementation to transfer to Geant4 and FLUKA

Running fluka
* Added many card options for FLUKA
* Added LOW-MAT card generation

FLUKA analysis
* Start of analysis classes for loading usrbnn 

Other 
* Fixed pybind11 change that caused test failure

### CODE REVIEW

**Comment by lnevay** [comment]
Looking good!

There's now 2 fluka modules though which perhaps we should avoid:

src/pyg4ometry/fluka
src/pyg4ometry/analysis/fluka

perhaps flukadata for the second?  (just remembering 'expressions')

**Comment by lnevay** [comment]
Out of curiosity, is this kind of style you or a pre-commit linting style:

```
c = _card.Card(
             "LOW-PWXS", what1=10010, what4=lowerMaterial, what5=upperMaterial
         )
```

This example is tirivial, but there are some bits where even the argument to `[]` accessor is split across lines and it seems to be to limit to a low character length lines. For me it's quite hard to read. If personal style, then totally fine, but if it's a pattern that will be applied automatically, maybe we can change it. 

```
 self.decomposed[
                     region
                 ] = pyg4ometry.pycgal.CGAL.PolygonDecomposition_2_wrapped(
                     self.cgalpolys[region]
                 )
```

**Comment by lnevay** [comment]
```
def Test(
     vis=False, interactive=False, fluka=True, writeNISTMaterials=False, outputPath=None
 ):
```
for the sake of 4 or 5 characters... 

Asking really for my own additions going forwards.

**Comment by lnevay** [comment]
pyg4ometry/fluka/extruder.py
pyg4ometry/analysis/fluka.py

The methods inside classes all use the `pep_underscore_notation()` but the rest of the code is `notThatStyle()`. 

I can change this to be consistent if ok?

**Comment by lnevay** [comment]
For the extruder, the interface is declare a name through a function, then append one point at a time. I might add a function to add a region with a list already so we don't force a loop on the user code side to put in a list.

**Comment by stewartboogert** [comment]
> pyg4ometry/fluka/extruder.py pyg4ometry/analysis/fluka.py
> 
> The methods inside classes all use the `pep_underscore_notation()` but the rest of the code is `notThatStyle()`.
> 
> I can change this to be consistent if ok?

Ok no problem. I am clearly exploring/experimenting with doing it the "proper" way

**Comment by stewartboogert** [comment]
> For the extruder, the interface is declare a name through a function, then append one point at a time. I might add a function to add a region with a list already so we don't force a loop on the user code side to put in a list.

``extruder.add_region`` returns a list so a user could use that. But the function would just add to the class

**Comment by stewartboogert** [comment]
> Looking good!
> 
> There's now 2 fluka modules though which perhaps we should avoid:
> 
> src/pyg4ometry/fluka src/pyg4ometry/analysis/fluka
> 
> perhaps flukadata for the second? (just remembering 'expressions')

Somehow I feel this is right with the module name spacing. We have many readers for example. I think the issue with expression is they were both mixed in the same area without a proper design etc.

**Comment by gipert** [comment]
> The methods inside classes all use the pep_underscore_notation() but the rest of the code is notThatStyle().

My strong preference is for [snake case](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Examples_of_multiple-word_identifier_formats) for function/method names), as of [PEP 8](https://peps.python.org/pep-0008/) :)

**Comment by gipert** [comment]
About auto-formatting. pre-commit uses black, which is based on PEPs and essentially gives no possibility to customize by design see [here](https://github.com/psf/black#the-black-code-style). As far as I saw nearly everyone uses it.

The reason why you see this:
```python
def Test(
     vis=False, interactive=False, fluka=True, writeNISTMaterials=False, outputPath=None
 ):
 ```

is because one single line would exceed the maximum number of characters allowed per line (88). I honestly hate when my editor needs to wrap code.

I would not mind, however, to [increase the maximum line length](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#l-line-length). 88 might be too short on modern high resolution monitors.

**Comment by lnevay** [comment]
Ok, now I realise we can't respond to individual messages here which makes my earlier ones a bit messy.

Regarding snake_case. My preference is also different, but the whole code is likeThisStyle(). I would really vote for consistency over mix and match. We have actually worked to make it more consistent as in the past some students just did their own style irrespective of the whole massive codebase.  In my group we have a decent amount of software built on pyg4ometry so I would really be against changing all the functions now and breaking all user code.

**Comment by lnevay** [comment]
To me, 88 characters is like < 1/3 of my laptop screen and the code becomes really unreadable, which is kind of opposite to the original intention.  My two cents.  I would favour marginally increasing it to like 95 or 100 if we can because so many are just for like 4 characters.

I agree ridiculously long lines with wrapping are bad.

**Comment by gipert** [comment]
> I would really vote for consistency over mix and match. We have actually worked to make it more consistent as in the past some students just did their own style irrespective of the whole massive codebase. In my group we have a decent amount of software built on pyg4ometry so I would really be against changing all the functions now and breaking all user code.

Yes I totally agree. It's more important to be consistent and such a change would anyways be quite painful, unless carefully planned.

**Comment by lnevay** [comment]
> > pyg4ometry/fluka/extruder.py pyg4ometry/analysis/fluka.py
> > The methods inside classes all use the `pep_underscore_notation()` but the rest of the code is `notThatStyle()`.
> > I can change this to be consistent if ok?
> 
> Ok no problem. I am clearly exploring/experimenting with doing it the "proper" way

Me too :)  Questions more orientated to what I *should* do in future for pyg4ometry.

**Comment by gipert** [comment]
>  I would favour marginally increasing it to like 95 or 100 if we can because so many are just for like 4 characters.

Agreed, 100 is anyways less than half of my screen. Sounds a good number to me.

Can you prepare a new PR with this? Should be in principle as easy as passing that command line argument to black as in here:

https://github.com/g4edge/pyg4ometry/blob/54b4ae0215e8f0b3e5e8325f61a2416c781b5f40/.pre-commit-config.yaml#L47-L52

and re-running pre-commit with `pre-commit run --all-files`.

**Comment by stewartboogert** [comment]
> > > pyg4ometry/fluka/extruder.py pyg4ometry/analysis/fluka.py
> > > The methods inside classes all use the `pep_underscore_notation()` but the rest of the code is `notThatStyle()`.
> > > I can change this to be consistent if ok?
> > 
> > 
> > Ok no problem. I am clearly exploring/experimenting with doing it the "proper" way
> 
> Me too :) Questions more orientated to what I _should_ do in future for pyg4ometry.

@lnevay We should keep it consistent. I'll stop pushing code to this repo in a new style.

**Pull request merged**
