### PR TITLE
github : action fix problem with python symlinks

### PR DESCRIPTION
**Pull request by stewartboogert**

### CODE REVIEW

**Comment by gipert** [comment]
uhmmmm maybe let's just add `--overwrite` to both brew calls...

**Comment by ManuelHu** [comment]
there were recent changes for `python@3.12` in homebrew: https://github.com/Homebrew/homebrew-core/commit/0b7a8eef3eea06df45e495a51470493776448383

**Comment by ManuelHu** [comment]
Some quick things I saw in the logs

* vtk depends on python@3.12
* azure-cli (why is this even installed??) depends on python@3.11

The latest good CI run did _not_ attempt to install azure-cli, and also not `python@3.12` (I am not sure why; as the dependency was certainly there already...)

**Comment by ManuelHu** [comment]
More research: In the default runner image, python@3.11 is default-symlinked. Maybe the update of python@3.11 to the latest (non-default) version does not remove all symlinks?

**Comment by ManuelHu** [comment]
#150 seems to fix the problem (sorry, I had no write permission to this PR's branch, so I had to create a new one)

**Comment by gipert** [comment]
green light from my side!

**Comment by ManuelHu** [comment]
Also no objections from me. At some later point the fixes probably can be removed (or commented out) again.

**Pull request merged**
