### PR TITLE
Update allowed OpticalSurface property values for G411.1

### PR DESCRIPTION
**Pull request by ManuelHu**
Also align the numeric ranges for the properties with the string lists.

### CODE REVIEW

**Comment by stewartboogert** [comment]
@gipert This appears to be a clash between the GitHub action python version installed and the brew version on Mac. I am not enitirely sure what the best way to proceed is as you have `brew install --overwrite python` which appears to be correct for the situation, but all the python tests fail.

**Comment by gipert** [comment]
I'm not sure I understand what's going on here. Related to the recent Python 3.12 stable release? What happens if we roll back with `brew install --overwrite python@3.11`? @ManuelHu could you try?

**Comment by gipert** [comment]
See #149

**Comment by ManuelHu** [comment]
@gipert what should I try? I hardly doubt that my changes did anything, and I also have no macOS system to test :-)

**Pull request merged**
